name: Release
# Build Docker Image and Push to GitHub Container Registry

on:
  # Action triggers on tagging version numbers
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  main-create-release-by-tag:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
